### UNSL - 2024
# Práctico 0-3:
## NumPy


Este práctico tiene como objetivo desarrollar programas en Python orientados al
procesamiento de datos a través de las facilidades provista por la extensión NumPy
de Python para manipulación eficiente de arreglos. Previo a la propuesta de los ejercicios,
esta "notebook" incluye la presentación de varios ejemplos como punto de partida para
facilitar el uso de las funciones para manipulación de arreglos provistas por NumPy.

En Ciencia de Datos, es por demás importante contar con funciones altamente eficientes
para manipular datos estructurados como arreglos provenientes de diferentes fuentes del
mundo real. Debe tenerse en cuenta que datos que puedan ser almacenados en arreglos pueden
provenir de muchas fuentes diversas:

### - imágenes
### - documentos de texto
### - sonidos
### - y mediciones numéricas en general

En síntesis, prácticamente todas las fuentes de datos, mas allá de lo que representen,
se puede almacenar en arreglos $n$-dimensionales (para $n \geq 1$). Así, una imagen puede
ser vista como una matriz númerica, similarmente para un documento de texto, por ejemplo
considerando la frecuencia de aparición de determinados vocablos, un arreglo sería la forma
más directa de almacenrlo. Una vez obtenidos esos datos, éstos se pueden procesar y
visualizar de diferentes maneras según estemos interesados en Análisis inteligente de
Datos o Apredizaje Automático, por mencionar algunas posibilidades.

### ***********************************************************************************
NumPy brinda muchas facilidades tanto para almacenamiento, como para procesamiento de datos
almacenados en arreglos $n$-dimensionales.

Antes que nada, es necesario incluir lo siguiente:

### import numpy as np

donde "np" es el nombre usado por convención. Daremos a continuación ejemplos de cada operación
de manipulación. Sin embargo, para cada caso, puede haber muchos ejemplos mas que es necesario
leer en detalle cada caso.

In [1]:
# Distintos ejemplos de creaciones de arreglos desde cero (from scratch) aunque se pueden crear
# a partir de listas.

import numpy as np
# crea un arrego de 10 componentes de tipo 'int' con valor incial 0
a = np.zeros(10, dtype=int)
# crea una matriz de 3x5 componentes de tipo 'float' con valor incial 1.0
b = np.ones((3, 5), dtype=float)
# crea una matriz de 3x5 componentes de tipo 'float' con valor incial 3.4
c = np.full((3, 5), 3.14)
print("a:\n", a)
print()
print("b:\n",b)
print()
print("c:\n",c)

a:
 [0 0 0 0 0 0 0 0 0 0]

b:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

c:
 [[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


In [2]:
# Crea un arreglo de 3x3 con valores aleatorios (uniforme) entre 0 y 1
a = np.random.random((3, 3))

# Crea una matriz de 3x3 con valores normalmente distribuídos con media 0 y desviación 1
b = np.random.normal(0, 1, (3, 3))
print("a:\n", a)
print()
print("b:\n",b)

a:
 [[0.68065787 0.3162303  0.37530108]
 [0.2469777  0.66291277 0.69482646]
 [0.01917014 0.86504234 0.80003397]]

b:
 [[ 1.97720061 -1.83577312  0.81976562]
 [ 2.28161627  0.89697383  0.47230645]
 [-0.79687774 -0.37202151  0.45372777]]


#### Es interesante ver la variedad de tipos de datos provistos por NumPy (ver el Libro "Handbook of Data Science in Python"). A menos que se indique otra cosa, se sugiere remitirse al libro antes mencionado para profundizar cuando sea necesario.

## Manipulación de datos básica en NumPy
### -- Atributos de los arreglos:
Determinar el tamaño, forma, consumo de memoria y tipos de datos.
### -- Sub-indicación (o indexación) de arreglos:
Recuperar y asignar el valor de elementos de arreglos
## -- Recuperar "tajadas" de un arreglo (Slicing)
Recuperar y agregar arreglos más pequeños de dentro de uno más grnde.
## -- "Reshaping" a un arreglo
Cambiar la forma de una arreglo dado.
## -- Juntar o dividir arreglos
Combinar múltiples arreglos en uno solo, y dividir un arreglo en varios
## ---------------------------------------------
Vemos ejemplos:

### Atributos

In [3]:
#codigo
import numpy as np
np.random.seed(0) # semilla para garantizar la reproducción de valores
x1 = np.random.randint(10, size=6) # arreglo unidimensional
x2 = np.random.randint(10, size=(3, 4)) # bidimensional (matriz)
x3 = np.random.randint(10, size=(3, 4, 5)) # Tridimensional (cubo)

# tres atributos (número de dimensiones, forma o tamaño de cada dimensión y tañano total del arreglo

# In[2]: print("x3 ndim: ", x3.ndim)
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print()
print(x1,"\n------\n",x2,"\n------\n", x3)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60

[5 0 3 3 7 9] 
------
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]] 
------
 [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


### Sub-indicación

In [4]:
# Codigo
print(x1[3])
print(x1[-2]) # acepta este valor negativo, cuenta desde el final
print(x2[2,1])
print(x2[2]) # fila 2 (ultima de x2)

3
7
6
[1 6 7 7]


### Slicing

In [5]:
# x[start, stop, step] (sintaxis: incio, final y paso)
x = np.arange(10)
print(x)
print(x[:5]) # desde el principio haste el quinto elemento
print(x[5:]) # desde el quinto hasta el final
print(x[3:6]) # entre el tercer y quinto elemento
print(x[2:8:2]) # desde el segundo haste el octavo, saltando de a 2

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[3 4 5]
[2 4 6]


In [6]:
# igual a lo anterior, se aplica para arreglos multidimensionales
print(x2)
print(x2[:2,:2])
print(x2[2:])
print(x2[1:2,2:4])
print(x2[1::2,3:])

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[3 5]
 [7 6]]
[[1 6 7 7]]
[[8 8]]
[[8]]


### Reshaping

In [7]:
grid = np.arange(1, 10)
print("grid antes\n", grid)
grid = grid.reshape((3, 3))
print("grid despues\n", grid)

grid antes
 [1 2 3 4 5 6 7 8 9]
grid despues
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# concatenar
x = np.array([1,2, 3])
y = np.array([3, 2, 1])
print(np.concatenate([x, y]))
z = [99, 99, 99]
print(np.concatenate([x, y, z]))
print("**********")

# división de arreglos
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5]) # 3 y 5 son el primer y segundo punto de corte
print(x1, x2, x3)
x1, x2, x3 = np.split(x, [2, 6])
print(x1, x2, x3)

[1 2 3 3 2 1]
[ 1  2  3  3  2  1 99 99 99]
**********
[1 2 3] [99 99] [3 2 1]
[1 2] [ 3 99 99  3] [2 1]


## Funciones Universales (ufuncs)

In [9]:
# Daremos algunos ejemplos, en particular usar operadores
# de expresiones arítmeticas para ser usados de manera directa sobre areglos
# aunque el uso de las ufuncs en mucho mas amplio, se recomienda consultar la bibliografúa propuesta
x = np.arange(9).reshape((3, 3))
print(2 ** x) # eleva al cuadrado cada componente de x
print()
print(2 * x) # multiplica cada compoente por 2 (a modo de escalar)

[[  1   2   4]
 [  8  16  32]
 [ 64 128 256]]

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [10]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


## Operadores de comparación como ufuncs

In [11]:
x = np.random.randint(10, size=18)
print(x)
print(x<4)
print(x == 4)
print(x>4)
print(x!=4)
print(x<=4)
print(x>=4)

[4 3 4 4 8 4 3 7 5 5 0 1 5 9 3 0 5 0]
[False  True False False False False  True False False False  True  True
 False False  True  True False  True]
[ True False  True  True False  True False False False False False False
 False False False False False False]
[False False False False  True False False  True  True  True False False
  True  True False False  True False]
[False  True False False  True False  True  True  True  True  True  True
  True  True  True  True  True  True]
[ True  True  True  True False  True  True False False False  True  True
 False False  True  True False  True]
[ True False  True  True  True  True False  True  True  True False False
  True  True False False  True False]


## Sub-indicación "Fancy" o "Elegante"

In [ ]:
#Se sugiere leer bibliografía (por tiempos acotados)

## Ordenamiento de arreglos y Datos estructurados (paso previo a Pandas)

In [ ]:
#Se sugiere leer bibliografía (por tiempos acotados

## Broadcasting y mas ...

In [ ]:
# Se sugiere leer bibliografía (por tiempos acotados). Vimos algunas gráficas en la primera clase
# a manera de ejemplo.

## Ejercicios propuestos

$\mathbf{Ejercicio} \,\,1$: Analizar todos los ejercicios del $\mathbf{Práctico\; 1}$ y determinar si
es posible usar NumPy para obtener un programa más compacto.

In [12]:
# Ejercicio 1
from random import uniform, seed

seed(10)
A = np.random.uniform(1, 100, 100)
print("Arreglo inicial:")
print(A)

A[(A <= 20) | (A >= 60)] = 0.
print("Arreglo modificado:")
print(A)

Arreglo inicial:
[62.66176346 67.69230345 97.22255525 87.94115366 51.4528133   6.51575468
 45.66476224  2.97877888 44.7293812  97.97908615 36.58500193 48.60845955
 69.1774571  88.16711304 91.90531117 22.46539163 56.95369779 86.64515357
 51.38792711 91.75557245 92.19460341  9.22813677 28.49413757  1.92631378
 84.39186589 65.07023988 84.2972258  27.20828626 40.38425452 55.72932651
 17.32910556 37.61100118 15.49773451 57.39222219 70.66999065 29.55916727
 43.89551814 75.85456269 40.21372927 89.70780036 64.25318655 89.26388929
 68.32550138 45.47057608 97.87852191 12.50398905 76.93534665 41.77019376
 67.86846904 25.72983129 32.00861486 96.57620583 59.25804342 66.30717279
 53.78741914 23.82276933 40.09206005 62.26204789 48.01188403 47.54308674
 71.89137859 29.51110943 38.96276028 75.16781388 87.96676684 11.18347251
 10.14501506 36.05061955 55.62980965  4.32888426 96.92721476 32.7787269
 22.90500583 14.98512659 10.62873278 98.4201819  26.77375183 54.16522962
 45.34469102 10.85733982 35.8788544

In [13]:
# Ejercicio 2
A = np.random.uniform(1, 100, 100)
print("Arreglo inicial:")
print(A)

B = A[(A <= 20) | (A >= 60)]
print("B:")
print(B)
A = A[(A >= 20) & (A <= 60)]
print("A:")
print(A)

Arreglo inicial:
[94.46822842 75.24992563 34.60097813 49.46534475 34.55952656 18.76953583
 17.92767327 46.88164676 87.58272281 94.46785534 61.21703372 60.06888522
 78.58078028 50.50260348  5.98663562 70.2107094  99.24724349 27.45899125
 68.22997095 86.56386283 75.33358032 96.48448701 55.87000107 22.02665939
 23.02187921 22.656188   57.38777992 45.75879447 97.05343163 68.37392443
  9.44426102  6.58541494 49.29593273 88.21945166 97.66403427 62.14813369
 54.70737873 85.60674445 74.63961999 48.38103624 68.03107583 61.09746105
 71.75499669 47.48022113 46.1454477  90.73539062 14.58482159 23.69271299
 88.27695452 90.53807259 64.93267525 33.14361423 52.45140817  1.00548033
 31.87416185 43.11970226 88.6484283  68.30806618 46.15684744 48.85745304
 79.08520333 23.71474161 88.14946271 32.05554686 95.78763471 47.70340552
 71.44679789 16.2157362  73.31377548 64.98017929 22.27319294 19.45936373
 80.95044662 74.96086754 67.80988725 28.41248133 18.31597856 70.74295158
 46.8518698  84.20242472 21.281710

In [14]:
# Ejercicio 3
# np.random es un generador
A = np.random.uniform(1, 100, 100)
print("Arreglo inicial:")
print(A)

A[(A <= 20) | (A >= 60)] = 0.
print("Arreglo modificado:")
print(A)

Arreglo inicial:
[18.98148885 51.72695287 58.46426658 78.96667344 61.04107055 22.62188263
 46.0617127  88.00810444 49.73455591 71.84055459 49.12979647 71.14626685
 50.31588233 84.61045787 20.23988007 77.55927495 97.45160772 86.36866796
 78.26223846 98.51819561 75.60339106  1.40076253 27.67846396 41.63872167
 43.39415938 30.48634004 40.71210181 12.94504213 98.08926773 41.20592881
 57.35186525 35.01694481 79.09840499 41.72586899 36.56787029 40.55039212
 30.88125672 77.74675797 92.69508009 33.20572021 95.33419657  2.3808912
 53.81310249 31.15362104 88.40313981 25.8116493  68.06377112 81.23198503
 43.78265694 75.46131758 83.13062254 38.52434344 10.55841137 26.35781816
 59.60158066 48.17124285 49.30552233 46.39294067 52.93466945 44.75951646
 85.41085745 43.91045847 82.86016646 51.42486447  9.55132106 66.34394636
 21.4528661  84.88025693 68.45455378 18.65836758  7.91604272  1.95912891
 89.31291615 14.21305575 78.14000545 92.59117916 71.80269615 49.59104267
 47.48033199 88.38821965 49.3525959

In [15]:
# Ejercicio 4
from math import sqrt

R = np.random.uniform(1, 10, 20)
M = np.random.uniform(1, 10, (100, 20))

dE = [sqrt(sum((R - m) ** 2)) for m in M]
print("Resultado:")
print(dE)

Resultado:
[15.707466751251928, 15.939887405942642, 13.420067180666678, 15.07811732016017, 17.07835245837738, 15.168522894479569, 20.01093255919253, 12.530153303635657, 15.530385521547728, 17.769475079305803, 14.759466308626404, 16.99173281546884, 14.06323196283077, 14.511540921342062, 18.03555817352357, 19.276593655724582, 17.54473034363456, 19.052499152926053, 12.055580316002523, 16.357376829965087, 18.68238505178142, 16.630550676203846, 17.749924435278764, 17.01699884060256, 18.908332752075786, 18.994805363489828, 15.656206892472992, 18.50556753044411, 14.993245701841117, 15.340512129459237, 16.115212801541766, 20.031022499510364, 18.364724691332857, 19.265692957124063, 16.608969449899334, 20.033077762349574, 17.36906820069691, 15.185819954542714, 20.784862958165615, 17.19013868040333, 17.980800489766235, 17.623612757957385, 15.455910647654408, 20.84382475641449, 16.921806575837035, 16.025542328256257, 15.343586107380418, 14.319349704737922, 18.288047766221304, 18.05726907531003, 16

In [16]:
# Ejercicio 5
matrix = list[list[int]]

def rand_matrix(rows: int, columns: int):
    return np.random.randint(1, 5, (rows, columns))

def mult_matrix(A, B):
    return np.matmul(A, B)

A = rand_matrix(20, 10)
B = rand_matrix(10, 30)

print(mult_matrix(A, B))

[[59 47 53 54 49 57 41 37 36 59 54 31 43 56 53 47 58 40 45 48 51 46 58 46
  46 62 62 53 47 47]
 [71 57 58 57 49 60 47 46 50 63 58 41 52 61 57 47 65 49 54 53 62 50 66 60
  65 71 66 67 60 47]
 [77 60 70 66 58 73 50 49 51 68 68 44 60 74 68 64 69 47 56 62 65 62 70 58
  62 78 79 61 57 62]
 [72 67 61 58 59 73 44 55 48 64 67 46 60 70 62 59 65 49 61 58 61 55 69 59
  66 80 77 66 57 54]
 [75 48 56 62 47 60 48 45 46 65 57 41 50 67 60 53 76 44 52 60 70 53 63 51
  61 66 68 64 60 51]
 [62 53 54 52 44 54 40 36 36 56 48 31 47 54 54 51 56 46 51 50 50 51 59 43
  53 65 64 58 47 39]
 [87 65 77 70 64 80 58 61 60 76 80 56 70 81 74 68 79 49 60 72 73 67 78 69
  71 92 90 68 63 69]
 [80 62 60 66 51 69 47 49 52 65 58 42 56 76 65 59 76 54 62 59 77 58 68 56
  73 69 71 72 67 55]
 [62 48 51 57 46 61 43 43 41 56 55 39 45 64 53 43 67 44 46 49 67 44 59 47
  58 59 63 60 54 50]
 [65 50 55 58 42 60 42 40 46 52 52 38 48 64 54 47 60 44 48 49 64 49 59 49
  62 58 59 57 55 49]
 [66 57 55 56 51 61 42 41 42 62 53 33 47 63 58 50 

In [17]:
# Ejercicio 6
A = rand_matrix(20, 10)
B = rand_matrix(10, 30)

C = mult_matrix(A, B)
D = C[0::2]
C = C[1::2]

print("C: ", C)
print("D: ", D)

C:  [[48 56 72 78 53 58 59 72 65 50 63 68 57 83 63 48 62 62 70 77 53 46 59 62
  78 74 57 55 80 72]
 [54 63 71 70 53 63 60 58 58 42 65 73 51 74 57 42 60 64 66 70 51 45 63 60
  73 74 64 59 76 70]
 [49 48 64 63 47 51 41 59 58 39 56 59 54 65 61 37 59 49 55 63 39 46 52 52
  73 66 45 51 72 68]
 [58 58 72 61 47 59 58 49 56 36 58 61 49 62 55 37 61 56 61 67 46 52 46 56
  68 63 62 54 71 64]
 [42 55 63 61 44 53 54 52 58 36 58 53 37 67 47 36 42 52 62 63 47 44 46 45
  52 52 57 49 64 53]
 [46 53 66 68 51 57 52 57 54 42 60 63 49 74 54 39 56 54 61 68 48 43 58 52
  67 67 55 48 73 66]
 [71 77 79 85 62 68 66 71 69 46 73 81 64 83 67 53 70 66 82 83 60 64 69 74
  90 79 71 70 89 84]
 [64 65 87 79 64 69 67 71 64 49 72 74 71 82 64 50 79 68 73 92 62 63 60 68
  85 76 72 66 89 78]
 [30 35 37 46 32 35 30 42 38 26 39 42 33 49 34 29 35 37 41 45 32 27 39 35
  46 44 32 36 47 44]
 [50 59 60 68 51 61 59 52 46 36 59 64 47 73 38 44 57 60 64 77 59 43 57 52
  61 62 63 53 70 59]]
D:  [[54 68 81 79 62 64 61 75 67 50 73 78 64 

In [18]:
# Ejercicio 7
T = np.random.uniform(-20, 20, 100)
Mask = np.random.rand(100) < 0.5

P = T[Mask]
N = T[np.invert(Mask)]

print("T: ", T)
print("Mask: ", Mask)
print("P: ", P)
print("N: ", N)

T:  [ 1.12608262e+01 -5.92854079e+00  1.14896344e+01  6.58775070e+00
 -1.64715803e+01  1.88419666e+01  1.72186880e+01  1.20738970e+01
  1.35349427e+01  4.82079934e+00  1.68022522e+01 -3.36849948e+00
  1.57369661e+01 -1.66902798e+00  1.12712415e+01 -9.76012156e-01
  7.88865953e+00 -2.69446161e+00 -4.75210252e+00  6.08116727e+00
  1.12710740e+01 -1.67418002e+01 -9.43639811e+00  3.54579426e+00
 -8.24450292e+00  3.24069590e+00  1.97357655e+01  1.54040948e+01
  3.10686077e+00 -1.72679783e+01  1.29144702e+01  1.80653059e+01
 -1.48886386e+01  4.75960581e+00 -1.40700752e+01 -1.55471918e+01
 -5.32202137e+00 -9.88171540e+00  9.43942057e+00 -1.09520667e+01
  1.38525069e+01 -1.03778042e+01  6.37671336e+00 -1.30096999e+01
  3.27426465e+00  1.52084023e-01  2.85522308e+00 -4.60245441e+00
  1.72122290e+01 -7.57968823e+00  1.63250571e+01  9.88398358e+00
 -5.34443849e+00 -1.65610885e+00  1.49118860e+01 -1.27811783e+01
 -1.38292799e+01  2.69514410e+00  1.92670767e+01 -5.03710106e-03
  4.60822853e+00  5.0

In [19]:
# Ejercicio 8
def get_cuadrant_2D(p: list[float]):
    x, y = p
    return (y < 0) << 1 | (x > 0) ^ (y > 0)

points = np.random.uniform(-100, 100, (500, 2))

count = np.zeros(4)

for p in points:
    count[get_cuadrant_2D(p)] += 1

print("Numero de puntos:")
for i in range(4):
    print('     Cuadrante {}: {}'.format(i + 1, count[i]))

Numero de puntos:
     Cuadrante 1: 132.0
     Cuadrante 2: 126.0
     Cuadrante 3: 113.0
     Cuadrante 4: 129.0


In [20]:
# Ejercicio 9
point = list[float]

points = np.random.uniform(-100, 100, (500, 2))

count = np.zeros(4)
acc = np.zeros((4, 2))

for p in points:
    cuad = get_cuadrant_2D(p)
    count[cuad] += 1
    acc[cuad] += p

print("Numero de puntos:")
for i in range(4):
    print('     Cuadrante {}: {}'.format(i + 1, count[i]))

print("Punto medio:")
for i in range(4):
    print('     Cuadrante {}: {}'.format(i + 1, [acc / len(points) for acc in acc[i]]))

Numero de puntos:
     Cuadrante 1: 110.0
     Cuadrante 2: 132.0
     Cuadrante 3: 113.0
     Cuadrante 4: 145.0
Punto medio:
     Cuadrante 1: [10.332189275230986, 11.723914877349577]
     Cuadrante 2: [-14.87280328127132, 14.139891781167389]
     Cuadrante 3: [-11.283609475786813, -10.024042312159658]
     Cuadrante 4: [15.457867127725311, -14.700725086614508]


In [21]:
# Ejercicio 10
def get_cuadrant_3D(p: point):
    x, y, z = p
    return (z < 0) << 2 | (y < 0) << 1 | (x > 0) ^ (y > 0)

points = np.random.uniform(-100, 100, (500, 3))

count = np.zeros(8)
acc = np.zeros((8, 3))

for p in points:
    cuad = get_cuadrant_3D(p)
    count[cuad] += 1
    acc[cuad] += p

print("Numero de puntos:")
for i in range(8):
    print('     Cuadrante {}: {}'.format(i + 1, count[i]))

print("Punto medio:")
for i in range(8):
    print('     Cuadrante {}: {}'.format(i + 1, [acc / len(points) for acc in acc[i]]))

Numero de puntos:
     Cuadrante 1: 73.0
     Cuadrante 2: 54.0
     Cuadrante 3: 43.0
     Cuadrante 4: 55.0
     Cuadrante 5: 75.0
     Cuadrante 6: 55.0
     Cuadrante 7: 68.0
     Cuadrante 8: 77.0
Punto medio:
     Cuadrante 1: [6.69689492501105, 7.2877503778760016, 7.254198833147507]
     Cuadrante 2: [-5.460886356714369, 5.616979779571186, 5.661917269103649]
     Cuadrante 3: [-3.635213450804335, -4.111770035057276, 4.129979521039827]
     Cuadrante 4: [5.432332732575034, -4.694482605263032, 5.33419266635979]
     Cuadrante 5: [7.383119892299975, 7.0463031016185, -7.5253284565492535]
     Cuadrante 6: [-4.725626776464906, 6.084185386089272, -5.365110460447939]
     Cuadrante 7: [-6.38662281849164, -7.994481141160794, -6.326845122817036]
     Cuadrante 8: [8.41829238340582, -7.964627492021734, -7.386666374040901]


$\mathbf{Ejercicio} \,\,2$: Dada una matriz $\mathbf{M}$ de $100\times 20$ con puntos generados
aleatoriamente en el intervalo continuo $[0,50]$ . Supongamos que dicha matriz representa un conjunto
de vectores (o "nube de puntos") en el espacio $n$-dimensional ($n=20$). Se pide, calcular el
$\mathit{centroide}$ de dicho conjunto de puntos.

In [22]:
M = np.random.uniform(0, 50, (100, 20))

centroid = np.add.reduce(M, 0) / 100
print("Centroide:")
print(centroid)

Centroide:
[21.96426701 25.44365571 28.69154625 26.63077441 24.16287039 26.63352785
 26.59682509 22.75767062 23.39170059 22.25258386 24.22351728 24.3752545
 25.64420298 28.0303886  24.80531806 24.96950959 24.40928145 26.70904065
 23.91730945 25.49199226]
